- name: Collect network device facts
  hosts: all
  gather_facts: no

  tasks:
    - name: Run show version
      cisco.iosxr.iosxr_command:
        commands:
          - show version
          - show interfaces
          - show ip route
      register: version_output

    - name: Save output
      copy:
        content: "{{ version_output.stdout[0] }}"
        dest: "./outputs/show_version_{{ inventory_hostname }}.txt"
