all:
  hosts:
    cisco_router:
      ansible_host: sandbox-iosxr-1.cisco.com
      ansible_user: developer
      ansible_password: C1sco12345
      ansible_network_os: iosxr
      ansible_connection: ansible.netcommon.network_cli
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

