all:
  hosts:
    cisco_router:
      ansible_host: sandbox-iosxr-1.cisco.com
      ansible_user: admin
      ansible_password: C1sco12345
      ansible_network_os: iosxr
      ansible_connection: network_cli
